// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/daily-os-variants/AmberTerminal.tsx": () => import("../components/mockups/daily-os-variants/AmberTerminal.tsx"),
  "./components/mockups/daily-os-variants/BentoGrid.tsx": () => import("../components/mockups/daily-os-variants/BentoGrid.tsx")
};
