import express, { type Express } from "express";
import cors from "cors";
import path from "path";
import "./types"; // Type augmentation for pino-http
import router from "./routes";
import { logger } from "./lib/logger";

// eslint-disable-next-line @typescript-eslint/no-var-requires, @typescript-eslint/no-explicit-any
const pinoHttp = require("pino-http") as any;

const app: Express = express();

app.use(
  pinoHttp({
    logger,
    serializers: {
      req(req: any) {
        return {
          id: req.id,
          method: req.method,
          url: req.url?.split("?")[0],
        };
      },
      res(res: any) {
        return {
          statusCode: res.statusCode,
        };
      },
    },
  }),
);
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// API routes
app.use("/api", router);

// SPA fallback: serve index.html for non-API routes
// In Vercel: index.html is served from /public (generated by Vite at root)
// The path is ../../../public from dist/index.js (dist → api-server → artifacts → root)
app.all("*", (_req, res) => {
  const indexPath = path.join(__dirname || process.cwd(), "../../../public/index.html");
  res.sendFile(indexPath);
});

export default app;
